dist: xenial

language: go

go:
  - 1.12.x

services:
  - docker

addons:
  apt:
    chrome: stable

script:
  - go test
  - go test -c
  - docker run --volume=$PWD:/chromedp --entrypoint=/chromedp/chromedp.test --workdir=/chromedp --env=CI=$CI --env=PATH=/headless-shell chromedp/headless-shell:latest
